export enum ContextType {
  ALL = 'all',
  PAGE = 'page',
  FRAME = 'frame',
  SELECTION = 'selection',
  LINK = 'link',
  EDITABLE = 'editable',
  IMAGE = 'image',
  VIDEO = 'video',
  AUDIO = 'audio',
  LAUNCHER = 'launcher',
  BROWSER_ACTION = 'browser_action',
  PAGE_ACTION = 'page_action',
  ACTION = 'action',
}
